### ISSUE TITLE
Title Open Science Room

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/outreach#2]
What do we call this?

State of BIDS PET? OpenNeuro's new PET Projects? Get your PET into the BIDS shape of its life?

**Comment by bendhouseart** [comment]
Tagging all of you that were in that meeting on this.

**Comment by CPernet** [comment]
I propose: PET BIDS and the OpenNeuroPET project

**Comment by bendhouseart** [comment]
Sounds good, I'm still not sure if we've managed to secure a room/venue or not. Current indications are that we just try to register the week of as it's first come first serve. So, we may not even get to use `PET BIDS and the OpenNeuroPET project` 👎

**Comment by bendhouseart** [comment]
It has been decided ~~~> PET BIDS and the OpenNeuroPET project
