### ISSUE TITLE
Achieve consensus on topic list.

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/outreach#4]
We briefly discussed covering:

- BEP 009
- Adding ECAT (better) support to Nibabel, pybids
- Other ongoing projects/efforts
- How to contribute/help; Uncle Sam need's you!

**Comment by CPernet** [comment]
- PET extension is now merged - remaining issues?
- Support for preparing data: Adding ECAT (better) support to Nibabel, pybids, dcm2nixx
- [BEP 023](https://docs.google.com/document/d/1yzsd1J9GT-aA0DWhdlgNr5LCu6_gvbjLyfvYq2FuxlY/edit) for derivatives is alive!
- Present your ongoing projects/effort: 
1. the [OpenNeuroPET](https://openneuropet.github.io/) project

**Comment by bendhouseart** [comment]
Sounds good to me @CPernet 

I'm pretty sure I could go on about this stuff for 10 to 15 at least, but what I'm really hoping for is a discussion. B/c well I think I can cover most of those topics pretty quickly :) Will add a markup doc tonight with some notes/outline.

**Comment by CPernet** [comment]
do we have an emergent session successfully booked - the [OSR schedule](https://ohbm.github.io/osr2021/schedule/) doesn't tell anything about those

**Comment by bendhouseart** [comment]
@CPernet No, they mentioned that that they wouldn't consider submissions before Monday and to submit then. see my previous submission [here](https://github.com/ohbm/osr2021/issues/5)

**Comment by melanieganz** [comment]
I dropped it on slack last night and it seems they are open now: https://ohbm.github.io/osr2021/schedule/ What time slot should we book? I would propose the 10 pm one tomorrow. Opinions?
